language: python
    
python: "3.6"
    
git:
  depth: 1

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations user
  - python manage.py makemigrations game
  - python manage.py migrate
  - coverage run manage.py test

after_success:
  - codecov